services:
  tp:
    image: eclipse-temurin:25-jre
    enviromnent:
      - DATABASE_URL
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8540:8540"
    entrypoint: >
      sh -c "java -jar --enable-native-access=ALL-UNNAMED tp.jar"

  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql

  redis:
    image: redis:8
    restart: unless-stopped
    volumes:
      - ./redis:/data

volumes:
  data:
    driver: local
