services:
  tp:
    image: eclipse-temurin:25-jre
    env_file: ".env"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8540:8540"
    entrypoint: >
      sh -c "java -jar --enable-native-access=ALL-UNNAMED target/typing-ex-5.1.1-standalone.jar"

  db:
    image: postgres:18
    env_file: ".env"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql

  redis:
    image: redis:8
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "127.0.0.1:16379:6379"

volumes:
  data:
    driver: local
