services:
  jre:
    image: eclipse-temurin:25_36-jre-jammy
    env_file: ".env"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3040:3000"
    entrypoint: >
      sh -c "java -jar --enable-native-access=ALL-UNNAMED tp.jar"

  db:
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:15432:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - ./db-dumps/redis:/data
    # ports:
    #   - 6380:6379

volumes:
  data:
    driver: local
  gitlibs:
    external: true
  m2:
    external: true
  # redis:
  #   driver: local
